//The sequence of triangle numbers is generated by adding the natural numbers.
//What is the value of the first triangle number to have over five hundred divisors?
//76576500
public class Problem12 {
	public static void main(String[] args) {
		int count = 0;
		int n = 76576500;
		for (int k = 1; k <= Math.sqrt(n); k++) {
			if (n % k == 0) {
				count++;

			}
		}
		System.out.println(count * 2);
		/* Triangle Code
		for (int i = 1; i < n; i++) {
			int sum = 0;
			int count1 = 0;
			String s = "";
			for (int j = 1; j <= i; j++) {
				sum += j;
			}
			s += (sum + ": " + "");
			for (int k = 1; k <= sum; k++) {
				if (sum % k == 0) {
					count1++;
					s += (k + "");
					if (k != sum)
						s += ",";
				}
			}
			System.out.print(s);
			System.out.println("");
			System.out.println(count1);
			if (count1 > 500)
				break;
		}
		*/
	}
}
